# -*- coding: utf-8 -*-
"""CsvFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5LWaSv9Pooo_rDKH94R-Sxdi-F7Se7V
"""

import csv

#Dictionary 
myDict = {'input1':20, 'input2':40,'input3':'tss'}
field_names = myDict.keys()
print(field_names)



with open('{}.csv'.format(name),'w') as csvfile:
  writer = csv.DictWriter(csvfile,fieldnames=field_names)
  writer.writeheader()
  writer.writerows([myDict])

csvfile.close()

with open('tab.csv','r') as f:
  print(f)
  d = csv.reader(f)
  print(d)
  Finput,output = [rows for rows in d]

  myDict = {Finput[x]:output[x] for x in range(0,len(Finput))}
f.close()

print(myDict)